### ISSUE TITLE
Bluetooth icon as arrow

### ISSUE THREAD

**Issue by ghost** [CopperBadger/dotfiles#2]
I saw you had changed a few things (two days ago), so I decided to look and see if there was anything I wanted to change in my setup. I noticed the new icon font, and thought I would update that. It worked smoothly, installing the font from the AUR and setting it as my font in i3_lemonbar_config, but one arrow (the one after the window icon and before the window title) shows up as a bluetooth icon. I believe it is set as `sep_right`. Do you know what could fix this? I'd guess that the non-conky part is trying to only use Siji, and that arrow is bluetooth in Siji, but the yellow workspace arrows seem to work.

Side note: What's the new stuff in the parser? Just wondering.

Thanks!

(I feel kinda bad doing this, seeing as I've opened the only two issues [that I know of], I hope I'm not bugging you!)

**Comment by CopperBadger** [comment]
It's no trouble at all-- I'm actually glad that someone's using my setup! Open as many tickets as you need. One of the changes in the parser file fixes the Bluetooth icon issue; if you update the `WSP)` section in your's, you should be good to go :)

The changes to the parser do a few things. The first is that since Siji has a "muted" icon, I use that instead of surrounding the volume with parentheses. The second change chops off the digit I added to workspace titles in `dots/.i3/config` to preserve the desired order while also using icons. The third change is the Bluetooth icon fix, and the last change is a very lame attempt at adding some visual effects / notification message commands that I probably won't use for anything without totally rewriting them.

**Comment by ghost** [comment]
~~I tried copying  the `WSP*)` from your parser to mine, but either Vim didn't do it right or it just didn't work. I looked over it and added a few ?'s where mine only had 3 and yours had 4. ~~

~~Am I pasting with Vim right? I copy it from your parser, go into Visual mode, highlight the old one, and press `p`.~~

Vim was pasting wrong, the new parser fixed it. Thanks!

**Comment by CopperBadger** [comment]
Great! No problem!
